# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wands',
            name='length',
            field=models.CharField(default='haha', max_length=250),
        ),
        migrations.AddField(
            model_name='wands',
            name='made_of',
            field=models.CharField(default='haha', max_length=250),
        ),
        migrations.AddField(
            model_name='wands',
            name='previous_owner',
            field=models.CharField(default='haha', max_length=250),
        ),
        migrations.AlterField(
            model_name='wands',
            name='price',
            field=models.IntegerField(),
        ),
    ]
